// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO24PYEk7I3Pq7EirZ3ywwapGSgvE7mzc',
    appId: '1:57114072055:web:cb0170361dd0bf1a0e14f2',
    messagingSenderId: '57114072055',
    projectId: 'library-of-dream-ff334',
    authDomain: 'library-of-dream-ff334.firebaseapp.com',
    storageBucket: 'library-of-dream-ff334.firebasestorage.app',
    measurementId: 'G-FR4Q1C0RHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1KzOHbxsD3bwNI52KSeTzRHxPUtMEiJA',
    appId: '1:57114072055:android:07a1505b9d03c9950e14f2',
    messagingSenderId: '57114072055',
    projectId: 'library-of-dream-ff334',
    storageBucket: 'library-of-dream-ff334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9cOI2kscGKVrI2qlCf-bE6hnBB0TZKk',
    appId: '1:57114072055:ios:50bf545f6f264ab00e14f2',
    messagingSenderId: '57114072055',
    projectId: 'library-of-dream-ff334',
    storageBucket: 'library-of-dream-ff334.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9cOI2kscGKVrI2qlCf-bE6hnBB0TZKk',
    appId: '1:57114072055:ios:50bf545f6f264ab00e14f2',
    messagingSenderId: '57114072055',
    projectId: 'library-of-dream-ff334',
    storageBucket: 'library-of-dream-ff334.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO24PYEk7I3Pq7EirZ3ywwapGSgvE7mzc',
    appId: '1:57114072055:web:2d974f2ebaf9dbde0e14f2',
    messagingSenderId: '57114072055',
    projectId: 'library-of-dream-ff334',
    authDomain: 'library-of-dream-ff334.firebaseapp.com',
    storageBucket: 'library-of-dream-ff334.firebasestorage.app',
    measurementId: 'G-NS48G7XF1L',
  );
}
